### ISSUE TITLE
Gmad is deleated by Kaspersky Internet Security immediately after launch

### ISSUE THREAD

**Issue by dvdvideo1234** [garrynewman/gmad#19]
So basically as it really says. I have Kaspersky IS 2016 installed on my rig and after I try to do anything with gmad.exe, KIS deletes it immediately. To resolve this I've added gmad.exe and gmpublish.exe to KIS2016's whitelist, and it does not do this amymore, However I prefer not to do that in case a virus slips trough KIS.

It will be nice to have a correction for this. Please tell me how can I help further !

**Comment by robotboy655** [comment]
Nothing we can do about it, report those files as false positive and hope that they will correct it.
