### ISSUE TITLE
Can't create .gma file

### ISSUE THREAD

**Issue by Justinh4x** [garrynewman/gmad#21]
I don't understand why I'm unable to create a file out of my folder containing the addon.

Here's my input into the terminal: /Users/santosbraun/Downloads/gmad_osx create -folder "/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_advanced_disguiser_606792331" -out "/Users/santosbraun/Desktop/frostygamers/terrortown/update/"

Terminal: Garry's Mod Addon Creator 1.1
Looking in folder "/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_advanced_disguiser_606792331/"
/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_advanced_disguiser_606792331/addon.json error: Couldn't find file

**Comment by robotboy655** [comment]
```on error: Couldn't find file```

The program cannot find ```/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_advanced_disguiser_606792331/addon.js```, which is required to create a .gma.

**Comment by Justinh4x** [comment]
My god, I forgot the addon.jason I feel stupid.

Thanks for the help!
