### ISSUE TITLE
Can't create file because apparently it doesn't fit the requierments

### ISSUE THREAD

**Issue by Justinh4x** [garrynewman/gmad#22]
This is the issue I get when I try to create a gma.file:

Santoss-MacBook-Pro:~ santosbraun$ /Users/santosbraun/Library/Application\ Support/Steam/steamapps/common/GarrysMod/bin/gmad_osx create -folder "/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_bomb_station_712675840" -out "/Users/santosbraun/Desktop/newgmadfiles"
Garry's Mod Addon Creator 1.1
Looking in folder "/Users/santosbraun/Desktop/frostygamers/terrortown/update/ttt_bomb_station_712675840/"
	.DS_Store
		[Not allowed by whitelist]
		[Filename contains captial letters]
	gamemodes/.DS_Store
		[Not allowed by whitelist]
		[Filename contains captial letters]
	gamemodes/terrortown/entities/entities/ttt_bomb_station/shared.lua
	gamemodes/terrortown/entities/weapons/weapon_ttt_bomb_station/shared.lua
	materials/.DS_Store
		[Not allowed by whitelist]
		[Filename contains captial letters]
	materials/vgui/ttt/icon_health.png
File list verification failed
-End

My question is, I'm editing a downloaded file from the workshop it makes no sense that I edited one line in the config and when I try to re-create the file this happens.

**Comment by robotboy655** [comment]
This is not a place to get help. Get help @ https://facepunch.com/forums/65

The errors and files that error are in the log itself. All you have to do is to use your eyes and look at the errors.

**Comment by Bo98** [comment]
This shouldn't even happen anymore: #18.
