### ISSUE TITLE
Lua: premake4.lua:1: attempt to call a nil value (global 'solution')

### ISSUE THREAD

**Issue by Minabsapi** [garrynewman/gmad#27]
Hello,
I tried to run the compiling toolchain for Windows, but when doing so Lua throws this error:
```
C:\Users\User\dir\gmad-master>..\lua-5.3.5_Win32_bi\lua53.exe premake4.lua --outdir="bin/" --bootil_lib="../bootil-master/lib/" --bootil_inc="../bootil-master/include/" vs2010
..\lua-5.3.5_Win32_bin\lua53.exe: premake4.lua:1: attempt to call a nil value (global 'solution')
stack traceback:
        premake4.lua:1: in main chunk
        [C]: in ?
```

Any idea of what could be wrong ?

**Comment by robotboy655** [comment]
https://premake.github.io/

**Comment by Minabsapi** [comment]
Downloaded the Windows version, the compilation is now done.
I would say thanks if I had an idea of what I must do now with the output files, which has nothing to do with the final binary I was looking for and expected...
