### ISSUE TITLE
GMad.sln compilation with VSCode 2017 throws errors

### ISSUE THREAD

**Issue by Minabsapi** [garrynewman/gmad#29]
## Global description
Tried to compile GMad using MSBuild, which throws errors.

## Steps to reproduce
1. Download GMad repository files and extract it
2. Download Bootil repository files and extract it
3. Premake GMad using the command `premake5 --outdir="bin/" --bootil_lib="<path to bootil's parent>/bootil/lib/windows/vs2017/" --bootil_inc="<path to bootil's parent>/bootil/include/" vs2017`
4. Premake Bootil lib in 'projects' using the command `premake5 vs2017`
5. Compile the output solution with the command `SET VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets& "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" Bootil.sln /p:Configuration=Release`
6. Put the output lib to 'lib/windows/vs2017'
7. Compile GMad using  `SET VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets& "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" GMad.sln /p:Configuration=Release`

## Expected output
The final binary 'gmad.exe' should appear in the 'bin' folder at the root of the GMad folder

## Obtained result
At step 7: 58 errors when compiling (two samples of these errors:)

```
bootil_static.lib(Buffer.obj) : error LNK2038: discordance found for 
'_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in 
create_gmad.obj [...\GMad.vcxproj]
```
```
bootil_static.lib(Tree.obj) : error LNK2001: unresolved external 
symbol __CrtDbgReport
 [...\GMad.vcxproj]
```

**Comment by robotboy655** [comment]
Dude you REALLY need to learn to google. You are compiling both in different debug/release levels smh.

**Comment by Minabsapi** [comment]
Listen.
I don't know sh** about compiling and I guess I'm not the only one. If you're so annoyed to see so many issues by someone thinking there's a problem because he's a complete noob in this kind of stuff (sorry, have to start somewhere), maybe considering to add compiled executable would be a good idea ? And no, it wouldn't be teaspooning, just avoiding this kind of fuss.
Obviously you shouldn't take it personally as you're not the curator of this repo. 

I'm sorry, I only have a little experience in global development and no experience at all with compiling and stuff. But the one who's the most annoyed is me and anybody who don't know what's going on, don't you think ?

Fyi, I always try my best to search long enough before opening this kind of issues. Don't know if I'm dumb or unlucky not to find anything relevant (that is wrong by the way, there's things I ended up figuring out myself fortunately), it's your choice. The only thing I know is that I'd rather find my way with websearches than spamming repos with issues closed some times later with an almost helpful note followed by a 'man you're kidding me' expression.

Also, may I ask what the hell are you talking about ? Both compilations were made with the '/p:Configuration=Release' flag. So how can these be different ?
I can't see anything wrong with the commands I provided earlier, they're almost the same. If you have an idea of what's wrong, please write it (or point me to the right direction), at least for the next lost noobs.

I know there's no reason for you to answer after all I wrote that may sound rude, but I'm asking just 
for you to stop being annoyed by my issues and me to stop banging my head on my desk these evenings.

**Comment by Bo98** [comment]
Maybe try the Visual Studio Dev Command Prompt so you don’t need to worry about paths and stuff. Might suddenly work.

If not I’ll maybe try it out myself later tonight or tomorrow.

**Comment by Minabsapi** [comment]
Alright, I will try that, thanks for the advise

**Comment by Minabsapi** [comment]
Tried what you told me, same result. Of course I restarted everything from scratch with this new solution.

**Comment by Minabsapi** [comment]
Retried again with a slightly different solution, still doesn't work.
Please, help me if you know. I can't figure it out myself, I'm out of ideas now.

**Comment by neico** [comment]
Why do you even try to compile this when you barely have experience with compiling and the like,
this application is shipped with gmod, why not just use it?

**Comment by Minabsapi** [comment]
1. Having no experience somewhere doesn't mean you don't have to try; one must start somewhere to get experience. But I'm stuck for now.
2. I thought the reason was obvious: maybe because I don't have the GMod ? 
If I had it, would you think I would be so stubborn at making GMad.exe myself ?

**Comment by neico** [comment]
Then what do you need gmad for, it's designed exclusively for gmod?

**Comment by Minabsapi** [comment]
I need to convert a user model with GMad. 
It can be used in standalone, and for what I need it works.

**Comment by Minabsapi** [comment]
Successfully compiled GMad under Linux. No other explanation than that Windows is terrible for compiling.
