### ISSUE TITLE
I need help...

### ISSUE THREAD

**Issue by Creeperaaron64** [garrynewman/gmad#30]
I need help using this because I'm not familiar with this. Can you please tell me what I need and what I have to do. Please can you help me.

**Comment by robotboy655** [comment]
This is not a place to "get help", especially if you don't tell us what you need help with, what difficulties you are having, what you are trying to do, anything really, etc.

You can get help with the game on the official Discord server: https://discord.gg/gmod

**Comment by Creeperaaron64** [comment]
Ok thank you.
