### ISSUE TITLE
Add flag to force extraction of files with "illegal characters in filename"

### ISSUE THREAD

**Issue by Cynosphere** [garrynewman/gmad#31]

**Comment by robotboy655** [comment]
They cannot be physically extracted because they contain illegal characters, that's why that warning was added.

**Comment by Cynosphere** [comment]
A lot of unicode that can be written, such as japanese character sets and emojis are getting blanketed by this though.

**Comment by Cynosphere** [comment]
Also why not just make the file become renamed so the file isn't lost either?

**Comment by sorenbug** [comment]
https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

See `NTFS` and `most UNIX file systems`. The problem comes when UTF-16 encoding drops a byte less than `0x20` due to a non-UTF-8 character.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/gmad/commit/57d9d68b7cc6a8a17c8260033d02ca1354cfacfb

This should be a much better approach that satisfies both criticisms.
