### ISSUE TITLE
Can't create *.gma files over 1.86gb (written 0 bytes! (Can't grow buffer?))

### ISSUE THREAD

**Issue by cuteexe** [garrynewman/gmad#33]
according to the news article we can now upload addons with up to 2gb in size (or even bigger). well i tried it. i was able to make a 1.61gb gma file and upload it to the workshop but never been able to create a bigger one. last test (1.86gb) failed with this error:

Failed to write file 'PATH TO A RANDOM FILE' - written 0 bytes! (Can't grow buffer?)
Failed to create the addon

had the same error before when i tried to make a 1.96gb addon

**Comment by xDShot** [comment]
>1.61gb
plz don't

**Comment by cuteexe** [comment]
why not?

**Comment by robotboy655** [comment]
You need more RAM to make the file. The error means it couldn't allocate more memory.

**Comment by cuteexe** [comment]
my pc has 32GB of ram wtf?

**Comment by whisperity** [comment]
If the binary is built 32-bit it really won't be able to use much memory...

**Comment by cuteexe** [comment]
i have the 64 bit chromium update installed and used the gmad.exe from within the bin directory

**Comment by robotboy655** [comment]
64 bit branch has 2 gmad.exe files, a 32bit one in GarrysMod/bin and a 64bit one in GarrysMod/bin/win64.

You need to use the latter one.

**Comment by cuteexe** [comment]
ohh wow now i feel stupid. thanks
